<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E5P6FT5" failures="1" tests="15" name="tests.BankScenarios" time="33.590" errors="0" timestamp="02 Oct 2023 15:50:17 GMT" skipped="0">
  <testcase classname="tests.BankScenarios" name="addUser" time="9.941">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.BankScenarios.addUser(BankScenarios.java:224)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- addUser -->
  <testcase classname="tests.BankScenarios" name="addCustomer" time="0.907"/>
  <testcase classname="tests.BankScenarios" name="addCustomer" time="6.145"/>
  <testcase classname="tests.BankScenarios" name="addCustomer" time="0.934"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="0.865"/>
  <testcase classname="tests.BankScenarios" name="addCustomer" time="2.099"/>
  <testcase classname="tests.BankScenarios" name="addCustomer" time="3.027"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="2.118"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="0.946"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="0.909"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="0.923"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="1.289"/>
  <testcase classname="tests.BankScenarios" name="performTransaction" time="1.606"/>
  <testcase classname="tests.BankScenarios" name="addCustomer" time="0.936"/>
  <testcase classname="tests.BankScenarios" name="addCustomer" time="0.945"/>
</testsuite> <!-- tests.BankScenarios -->
